// Mock data for Clinical domain testing
// Since the Clinical domain has 0 nodes in KG, we use mock data for UI testing

import { ClinicalTrial, Condition, Intervention, Location, Outcome } from './types';

export const mockClinicalTrials: ClinicalTrial[] = [
  {
    id: 'NCT00001234',
    nctId: 'NCT00001234',
    title: 'A Phase 3 Study of Drug X for Treatment of Advanced Non-Small Cell Lung Cancer',
    phase: 'Phase 3',
    status: 'Active, not recruiting',
    studyType: 'Interventional',
    startDate: '2023-01-15',
    completionDate: '2025-06-30',
    enrollment: 450,
    allocation: 'Randomized',
    masking: 'Double-blind',
    purpose: 'Treatment',
    conditions: ['Lung Cancer', 'Non-Small Cell Lung Cancer', 'Carcinoma'],
    sponsors: ['Pfizer Inc.', 'Merck & Co.'],
    collaborators: ['National Cancer Institute'],
  },
  {
    id: 'NCT00001235',
    nctId: 'NCT00001235',
    title: 'Efficacy and Safety of Antibody Y in Patients With Rheumatoid Arthritis',
    phase: 'Phase 2',
    status: 'Recruiting',
    studyType: 'Interventional',
    startDate: '2023-03-01',
    completionDate: '2024-12-31',
    enrollment: 280,
    allocation: 'Randomized',
    masking: 'Double-blind',
    purpose: 'Treatment',
    conditions: ['Rheumatoid Arthritis', 'Arthritis'],
    sponsors: ['AbbVie Inc.'],
    collaborators: ['Harvard Medical School'],
  },
  {
    id: 'NCT00001236',
    nctId: 'NCT00001236',
    title: 'Comparison of Two Treatment Regimens in Type 2 Diabetes Mellitus',
    phase: 'Phase 4',
    status: 'Completed',
    studyType: 'Interventional',
    startDate: '2020-05-10',
    completionDate: '2023-08-15',
    enrollment: 1200,
    allocation: 'Randomized',
    masking: 'Open Label',
    purpose: 'Treatment',
    conditions: ['Diabetes Mellitus, Type 2', 'Diabetes'],
    sponsors: ['Novo Nordisk'],
    collaborators: ['Mayo Clinic'],
  },
  {
    id: 'NCT00001237',
    nctId: 'NCT00001237',
    title: 'Gene Therapy for Inherited Retinal Disease',
    phase: 'Phase 1/Phase 2',
    status: 'Recruiting',
    studyType: 'Interventional',
    startDate: '2023-06-01',
    completionDate: '2025-12-01',
    enrollment: 45,
    allocation: 'Non-randomized',
    masking: 'None',
    purpose: 'Treatment',
    conditions: ['Retinal Degeneration', 'Inherited Retinal Disease'],
    sponsors: ['Spark Therapeutics'],
    collaborators: ['NIH NEI'],
  },
  {
    id: 'NCT00001238',
    nctId: 'NCT00001238',
    title: 'Observational Study of Disease Progression in Alzheimer\'s Disease',
    phase: 'N/A',
    status: 'Active, not recruiting',
    studyType: 'Observational',
    startDate: '2022-09-01',
    completionDate: '2027-09-01',
    enrollment: 500,
    allocation: 'N/A',
    masking: 'None',
    purpose: 'Observational',
    conditions: ['Alzheimer Disease', 'Dementia', 'Cognitive Decline'],
    sponsors: ['National Institute on Aging'],
    collaborators: ['Alzheimer\'s Association'],
  },
  {
    id: 'NCT00001239',
    nctId: 'NCT00001239',
    title: 'CAR-T Cell Therapy for Refractory Multiple Myeloma',
    phase: 'Phase 2',
    status: 'Recruiting',
    studyType: 'Interventional',
    startDate: '2023-04-15',
    completionDate: '2025-03-31',
    enrollment: 150,
    allocation: 'Single-group',
    masking: 'None',
    purpose: 'Treatment',
    conditions: ['Multiple Myeloma', 'Plasma Cell Neoplasm'],
    sponsors: ['Bristol Myers Squibb'],
    collaborators: ['Dana-Farber Cancer Institute'],
  },
  {
    id: 'NCT00001240',
    nctId: 'NCT00001240',
    title: 'Vaccine Efficacy Study for COVID-19 Prevention',
    phase: 'Phase 3',
    status: 'Completed',
    studyType: 'Interventional',
    startDate: '2021-02-01',
    completionDate: '2022-12-31',
    enrollment: 30000,
    allocation: 'Randomized',
    masking: 'Double-blind',
    purpose: 'Prevention',
    conditions: ['COVID-19', 'SARS-CoV-2 Infection'],
    sponsors: ['ModernaTX, Inc.'],
    collaborators: ['NIH NIAID'],
  },
  {
    id: 'NCT00001241',
    nctId: 'NCT00001241',
    title: 'Novel Anticoagulant for Atrial Fibrillation Stroke Prevention',
    phase: 'Phase 3',
    status: 'Recruiting',
    studyType: 'Interventional',
    startDate: '2023-07-01',
    completionDate: '2026-06-30',
    enrollment: 18000,
    allocation: 'Randomized',
    masking: 'Double-blind',
    purpose: 'Prevention',
    conditions: ['Atrial Fibrillation', 'Stroke'],
    sponsors: ['Johnson & Johnson'],
    collaborators: ['American Heart Association'],
  },
];

export const mockConditions: Condition[] = [
  { id: 'C00001', name: 'Lung Cancer', code: 'C34.9', trialCount: 1234, phase: 'Phase 3' },
  { id: 'C00002', name: 'Non-Small Cell Lung Cancer', code: 'C34.90', trialCount: 892, phase: 'Phase 3' },
  { id: 'C00003', name: 'Rheumatoid Arthritis', code: 'M05.9', trialCount: 645, phase: 'Phase 2' },
  { id: 'C00004', name: 'Diabetes Mellitus, Type 2', code: 'E11.9', trialCount: 2134, phase: 'Phase 4' },
  { id: 'C00005', name: 'Alzheimer Disease', code: 'G30.9', trialCount: 987, phase: 'Phase 2' },
  { id: 'C00006', name: 'Multiple Myeloma', code: 'C90.0', trialCount: 543, phase: 'Phase 2' },
  { id: 'C00007', name: 'COVID-19', code: 'U07.1', trialCount: 3456, phase: 'Phase 3' },
  { id: 'C00008', name: 'Atrial Fibrillation', code: 'I48.91', trialCount: 765, phase: 'Phase 3' },
  { id: 'C00009', name: 'Breast Cancer', code: 'C50.9', trialCount: 1876, phase: 'Phase 3' },
  { id: 'C00010', name: 'Colorectal Cancer', code: 'C18.9', trialCount: 1098, phase: 'Phase 3' },
  { id: 'C00011', name: 'Prostate Cancer', code: 'C61.9', trialCount: 945, phase: 'Phase 3' },
  { id: 'C00012', name: 'Hypertension', code: 'I10', trialCount: 2341, phase: 'Phase 4' },
];

export const mockInterventions: Intervention[] = [
  {
    id: 'I00001',
    trialId: 'NCT00001234',
    interventionType: 'Drug',
    name: 'Drug X',
    description: 'Novel small molecule inhibitor',
    dosage: '200 mg twice daily',
    frequency: 'Every 12 hours',
    armGroupLabel: 'Experimental',
  },
  {
    id: 'I00002',
    trialId: 'NCT00001234',
    interventionType: 'Drug',
    name: 'Placebo',
    description: 'Matching placebo',
    dosage: '200 mg twice daily',
    frequency: 'Every 12 hours',
    armGroupLabel: 'Placebo',
  },
  {
    id: 'I00003',
    trialId: 'NCT00001235',
    interventionType: 'Biological',
    name: 'Antibody Y',
    description: 'Humanized monoclonal antibody',
    dosage: '150 mg subcutaneous injection',
    frequency: 'Every 4 weeks',
    armGroupLabel: 'Experimental',
  },
  {
    id: 'I00004',
    trialId: 'NCT00001236',
    interventionType: 'Drug',
    name: 'Drug Z',
    description: 'SGLT2 inhibitor',
    dosage: '10 mg once daily',
    frequency: 'Every 24 hours',
    armGroupLabel: 'Experimental',
  },
  {
    id: 'I00005',
    trialId: 'NCT00001237',
    interventionType: 'Genetic',
    name: 'Gene Therapy Vector',
    description: 'AAV-mediated gene delivery',
    dosage: 'Single intravitreal injection',
    frequency: 'One time',
    armGroupLabel: 'Experimental',
  },
  {
    id: 'I00006',
    trialId: 'NCT00001239',
    interventionType: 'Biological',
    name: 'CAR-T Cells',
    description: 'Autologous T cells engineered to express BCMA-directed CAR',
    dosage: 'Target dose 450 x 10^6 CAR-positive T cells',
    frequency: 'Single infusion',
    armGroupLabel: 'Experimental',
  },
];

export const mockOutcomes: Outcome[] = [
  {
    id: 'O00001',
    trialId: 'NCT00001234',
    outcomeType: 'Primary',
    title: 'Overall Survival',
    description: 'Time from randomization to death from any cause',
    timeFrame: 'Up to 36 months',
    category: 'Survival',
  },
  {
    id: 'O00002',
    trialId: 'NCT00001234',
    outcomeType: 'Secondary',
    title: 'Progression-Free Survival',
    description: 'Time from randomization to disease progression or death',
    timeFrame: 'Up to 36 months',
    category: 'Survival',
  },
  {
    id: 'O00003',
    trialId: 'NCT00001235',
    outcomeType: 'Primary',
    title: 'ACR20 Response at Week 12',
    description: 'Percentage of participants achieving ACR20 response',
    timeFrame: 'Week 12',
    category: 'Efficacy',
  },
  {
    id: 'O00004',
    trialId: 'NCT00001236',
    outcomeType: 'Primary',
    title: 'Change in HbA1c',
    description: 'Change from baseline in glycated hemoglobin',
    timeFrame: 'Baseline to Week 26',
    category: 'Metabolic',
  },
];

export const mockLocations: Location[] = [
  {
    id: 'L00001',
    trialId: 'NCT00001234',
    facility: 'Memorial Sloan Kettering Cancer Center',
    city: 'New York',
    state: 'New York',
    country: 'United States',
    status: 'Recruiting',
    latitude: 40.7644,
    longitude: -73.9553,
  },
  {
    id: 'L00002',
    trialId: 'NCT00001234',
    facility: 'MD Anderson Cancer Center',
    city: 'Houston',
    state: 'Texas',
    country: 'United States',
    status: 'Recruiting',
    latitude: 29.7245,
    longitude: -95.3544,
  },
  {
    id: 'L00003',
    trialId: 'NCT00001234',
    facility: 'Dana-Farber Cancer Institute',
    city: 'Boston',
    state: 'Massachusetts',
    country: 'United States',
    status: 'Recruiting',
    latitude: 42.3368,
    longitude: -71.0988,
  },
  {
    id: 'L00004',
    trialId: 'NCT00001234',
    facility: 'Charité - Universitätsmedizin Berlin',
    city: 'Berlin',
    country: 'Germany',
    status: 'Recruiting',
    latitude: 52.5200,
    longitude: 13.4050,
  },
  {
    id: 'L00005',
    trialId: 'NCT00001234',
    facility: 'The Royal Marsden Hospital',
    city: 'London',
    country: 'United Kingdom',
    status: 'Active, not recruiting',
    latitude: 51.4932,
    longitude: -0.1886,
  },
];

export const mockTrialDetail: ClinicalTrial = {
  ...mockClinicalTrials[0],
  interventions: [mockInterventions[0], mockInterventions[1]],
  outcomes: [mockOutcomes[0], mockOutcomes[1]],
  locations: mockLocations.filter(l => l.trialId === 'NCT00001234'),
};

export const mockStatistics = {
  totalTrials: 423456,
  activeTrials: 98765,
  completedTrials: 287654,
  recruitingTrials: 45678,
  totalConditions: 8765,
  totalInterventions: 12345,
  avgEnrollment: 156,
  phaseDistribution: {
    'Phase 1': 54321,
    'Phase 2': 87654,
    'Phase 3': 65432,
    'Phase 4': 9876,
    'N/A': 206173,
  },
  statusDistribution: {
    'Recruiting': 45678,
    'Active, not recruiting': 32098,
    'Completed': 287654,
    'Terminated': 12345,
    'Suspended': 4567,
    'Withdrawn': 2345,
    'Other': 38769,
  },
};
